remote_theme: rosario/kasper

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


#title: COVID-19 European Regional Tracker
#description: Tracking the spread of COVID-19 across NUTS3 and NUTS2 regions in 26 European countries.


author: 
  name: Asjad Naqvi
  twitter: asjadnaqvi