remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

title: COVID-19 European Regional Tracker
description: Tracking the spread of COVID-19 across NUTS3 and NUTS2 regions in 26 European countries.


author: 
  name: Asjad Naqvi
  twitter: asjadnaqvi